# Notice the v1beta3 version
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: dynamic-field-template
  title: Dynamic Field Template
  description: Showcase using dynamic fields in Backstage template
spec:
  owner: backstage/techdocs-core
  type: service
  parameters:
    - title: Demo Dynamic Field
      properties:
        teams:
          type: string
          # Use `SelectFieldFromApi` to configure the select field for the entry.
          ui:field: SelectFieldFromApi
          ui:options:
            title: Teams
            description: ""
            # The Path on the Backstage API and the parameters to fetch the data for the dropdown
            path: 'proxy/resources/teams'
            placeholder: 'Select from options'
            arraySelector: 'teams'
        users:
          type: string
          # Use `SelectFieldFromApi` to configure the select field for the entry.
          ui:field: SelectFieldFromApi
          ui:options:
            title: Users
            description: ""
            # The Path on the Backstage API and the parameters to fetch the data for the dropdown
            path: 'proxy/resources/users'
            placeholder: 'Select from options'
            arraySelector: 'users'
        groups:
          type: string
          # Use `SelectFieldFromApi` to configure the select field for the entry.
          ui:field: SelectFieldFromApi
          ui:options:
            title: Groups
            description: ""
            # The Path on the Backstage API and the parameters to fetch the data for the dropdown
            path: 'proxy/resources/groups'
            placeholder: 'Select from options'
            arraySelector: 'groups'
        api_frameworks:
          type: string
          # Use `SelectFieldFromApi` to configure the select field for the entry.
          ui:field: SelectFieldFromApi
          ui:options:
            title: APIFrameworks
            description: ""
            # The Path on the Backstage API and the parameters to fetch the data for the dropdown
            path: 'proxy/resources/api-frameworks'
            placeholder: 'Select from options'
            arraySelector: 'api-frameworks'
  # here's the steps that are executed in series in the scaffolder backend
  steps:
    - id: display-fields
      name: Display fields
      action: debug:log
      input:
        message: Hello ${{ parameters.teams }} ${{ parameters.users }} ${{ parameters.groups }} ${{ parameters.api_frameworks }}!
  # some outputs which are saved along with the job for use in the frontend
  output:
    text:
      - title: More information
        content: |
          Hello ${{ parameters.teams }} ${{ parameters.users }} ${{ parameters.groups }} ${{ parameters.api_frameworks }}!
